os: linux
dist: focal
language: c

install:
 - sudo apt-get update
 - sudo apt-get install --yes libgtest-dev
 - sudo apt-get install --yes gcovr
 
 script:
 - cmake -B build
 - make -C build
 - cd build && ctest --output-on-failure
