name: CI
on: [push]

jobs:

# сборка проекта
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: cd src && sudo mkdir build && cd build && sudo cmake .. && sudo make
      - run: ls

# соотсветствие формату написания кода
  formatting-check:
    name: Format checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '13'
        check-path: 'src''include'
        
# Статический анализатор кода
  cpp-check:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -qq update
    - run: sun apt-get install cppcheck
    - run: sudo cppcheck src/main.c src/count_symbols_sequence.c src/count_symbols_thread.c src/file_interaction.c src/time_test.c include/file_interaction.h include/stucture_t.h
    
    
  
