name: CI
on: [push]

jobs:

# сборка проекта
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - run: ls
      - run: sudo apt-get install -y libgtest-dev
      - run: sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
      - run: sudo tar -xf release-1.7.0.tar.gz
      - run: cd googletest-release-1.7.0
      - run: sudo cmake
      - run: sudo make googletest-release-1.7.0
      - run: sudo mkdir build && cd build && sudo cmake .. && sudo make
      - run: ls

# соотсветствие формату написания кода
  formatting-check:
    name: Format checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.2.0
      with:
        clang-format-version: '13'
        check-path: 'src''include'
        
# Статический анализатор кода
  cpp-check:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get -qq update
    - run: sudo apt-get install cppcheck
    - run: sudo cppcheck --enable=all --inconclusive --language=c ./src
    
    
  
